"""initial

Revision ID: d1f86d2dbfad
Revises: 
Create Date: 2026-05-10 18:04:31.251652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f86d2dbfad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('slug', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name_ja', sa.String(length=300), nullable=True),
    sa.Column('name_en', sa.String(length=300), nullable=True),
    sa.Column('name_kana', sa.String(length=300), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_artist_source_ext')
    )
    op.create_index(op.f('ix_artists_slug'), 'artists', ['slug'], unique=False)
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title_canonical', sa.String(length=500), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_relations',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_label_raw', sa.String(length=300), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=300), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_release_source_ext')
    )
    op.create_table('editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('price_raw', sa.String(length=200), nullable=True),
    sa.Column('price_jpy', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('release_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=False),
    sa.Column('condition', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=300), nullable=True),
    sa.Column('acquired_date', sa.Date(), nullable=True),
    sa.Column('acquired_price', sa.Integer(), nullable=True),
    sa.Column('acquired_from', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edition_id')
    )
    op.create_table('discs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('disc_type', sa.String(length=10), nullable=True),
    sa.Column('catalog_no', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discs_catalog_no'), 'discs', ['catalog_no'], unique=False)
    op.create_table('iso_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=True),
    sa.Column('nas_path', sa.String(length=1000), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nas_path')
    )
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disc_id', sa.Integer(), nullable=False),
    sa.Column('index_no', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('suffix', sa.String(length=200), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('track_credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('credit_text', sa.Text(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_clips')
    op.drop_table('track_credits')
    op.drop_table('tracks')
    op.drop_table('iso_files')
    op.drop_index(op.f('ix_discs_catalog_no'), table_name='discs')
    op.drop_table('discs')
    op.drop_table('collection_items')
    op.drop_table('release_images')
    op.drop_table('editions')
    op.drop_table('releases')
    op.drop_table('artist_relations')
    op.drop_table('songs')
    op.drop_index(op.f('ix_artists_slug'), table_name='artists')
    op.drop_table('artists')
    # ### end Alembic commands ###
